# Site settings
name: Ming's blog
email: fangming89@gmail.com
author: Fangming Zheng
url: http://fangmingzheng.github.io/ming
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/fangmingzheng/
baseurl: ""
description: Actually, less is more!
meta_description: 生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: fangmingzheng

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

